name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SFTP Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ftp.evelinyjhovanabeauty.com
          username: admin@evelinyjhovanabeauty.com
          password: rUV2QlXB%l{w
          source: "."
          target: "/"
