name: Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 108.179.193.140
          username: admin@evelinyjhovanabeauty.com
          password: rUV2QlXB%l{w
          dangerousCleanSlate: true

