name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install lftp

      - name: Sync files to FTP
        run: |
          lftp -f "
          open ftp://admin@evelinyjhovanabeauty.com:password@108.179.193.140
          mirror -R ./ ./public_html
          bye
          "
